### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by Mala2** [bernebeer/Charge-n-Boost#2]
I was wondering if you don’t mind sharing the BOM as I am having a hard time choosing the right MOSFET for the LED

Thanks a lot
<img width="788" alt="Screen Shot 2021-03-20 at 6 48 21 PM" src="https://user-images.githubusercontent.com/63622787/111891084-10416200-89ad-11eb-88f0-e4e9b832bb60.png">

**Comment by bernebeer** [comment]
Hi Mala,

Thanks for your interest :) It's been some time since I've taken  a look at this project, unfortunately pretty much dead in the water at the moment. Please bear in mind the schematics and code might not conform. As to the mosfet and transistor combo I remember copying a Teensy schematic someone suggested but cannot find it. Will have a look but might take some time as I do not have direct access to the BOM at the moment, will get back shortly.

Regards,

Gijs

**Comment by bernebeer** [comment]
Hi again,

I've uploaded a semblance of a BOM :) It seems Q1 is an FDV304P and Q2 is an MMBT3904. I don't remember ever having tested this combination on a physical PCB, so mileage may vary.

Regards,

Gijs

**Comment by bernebeer** [comment]
Having piqued interest, had a look at why the transistor combo was needed. Perhaps superfluous but still. It seems ws2812b's consume about a mA even when idle. In powerbank terms a massive waste. So, a cutoff switch was necessary when not using ws2812 led with 5v applied to VDD. At -5v Vgs the Rdson of this mosfet is 1 ohm at 0.5A. Seems wasteful but remember using this part because I had it lying around. Anyway, perhaps better parts are available.

Regards,

Gijs

**Comment by Mala2** [comment]
Thanks a lot for your reply, It did help me a lot.

Another question if you don’t mind, is the power always live after the BQ25895 from SW pin as I am wondering why did you choose to power the Atmega328 from the BAT pin, not the SW pin?

Sorry for any inconvenience I may have caused. I am working on Bluetooth Portable Speaker and I intended to use your charging system you may take a look at the GitHub link https://github.com/Mala2/Bluetooth-Speaker.

I will definitely appreciate any input from you and I will be happy to link your repository to mine as a reference.

Thanks a lot for your time
